init:
  - opened_fridge(fridge_push_point)

goal:
  expr_type: AND
  sub_exprs:
    - at(obj0_target|0,TARGET_obj0_target|0)
    - at(obj1_target|1,TARGET_obj1_target|1)

objects:
  - name: obj0_target|0
    expr_type: rigid_obj_type
  - name: TARGET_obj0_target|0
    expr_type: goal_type

  - name: obj1_target|1
    expr_type: rigid_obj_type
  - name: TARGET_obj1_target|1
    expr_type: goal_type

  - name: ROBOT_0
    expr_type: robot_type
  - name: ROBOT_1
    expr_type: robot_type

  # Receptacles.
  - name: frl_apartment_sofa_:0000
    expr_type: recep_type
  - name: frl_apartment_chair_01_:0000
    expr_type: recep_type
  - name: frl_apartment_table_01_:0000
    expr_type: recep_type
  - name: frl_apartment_tvstand_:0000
    expr_type: recep_type
  - name: frl_apartment_table_02_:0000
    expr_type: recep_type
  - name: frl_apartment_table_03_:0000
    expr_type: recep_type


stage_goals:
  stage_0_5:
    expr_type: AND
    quantifier: EXISTS
    inputs:
      - name: robot
        expr_type: robot_type
    sub_exprs:
      - holding(obj0_target|0, robot)
  stage_1:
    expr_type: AND
    sub_exprs:
      - at(obj0_target|0,TARGET_obj0_target|0)
  stage_1_5:
    expr_type: AND
    quantifier: EXISTS
    inputs:
      - name: robot
        expr_type: robot_type
    sub_exprs:
      - holding(obj1_target|1, robot)
  stage_2:
    expr_type: AND
    sub_exprs:
      - at(obj1_target|1,TARGET_obj1_target|1)

solution: []
