ENVIRONMENT:
    MAX_EPISODE_STEPS: 750
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/train/tidy_house_10k_1k.json.gz
    SCENES_DIR: data/replica_cad/
TASK:
    TYPE: RearrangeCompositeTask-v0
    REWARD_MEASURE: cooking_reward
    SUCCESS_MEASURE: composite_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: -0.001
    END_ON_SUCCESS: true
    MAX_COLLISIONS: -1.0
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false
    CONSTRAINT_VIOLATION_ENDS_EPISODE: false
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    EASY_INIT: false

    ROBOT_AT_THRESH: 1.5
    ROBOT_AT_ANGLE: 0.52  # 30 degrees
    #ROBOT_AT_ANGLE: 10000.0

    EFFICIENCY:
      TYPE: EfficiencyMetric
      STEPS: 500

    TASK_SPEC_BASE_PATH: bdp/config/tasks/pddl/
    PDDL_DOMAIN_DEF: bdp/config/tasks/pddl/domain.yaml
    
    TASK_SPEC: tidy_house_multi
    OBJ_SUCC_THRESH: 0.3
    ART_SUCC_THRESH: 0.15
    COMPOSITE_SUCCESS:
      MUST_CALL_STOP: False
    COOKING_REWARD:
      TYPE: CookingReward
      REQUIRE_STAGE_ORDER: False
      GIVE_STAGE_REWARDS: True
      END_ON_COLLIDE: False
      # Should be positive or 0.
      COLLIDE_PENALTY: 0.0
      STAGE_SPARSE_REWARD: 
        stage_bowl_1: 0.5
        stage_bowl_2: 0.5
        stage_bowl_3: 0.5
        stage_bowl_4: 0.5
        stage_bowl_5: 0.5
        stage_fruit_1: 0.5
        stage_fruit_2: 0.5
        stage_fruit_3: 0.5
        stage_fruit_4: 0.5
        stage_fruit_5: 0.5

        # Used in tidy house
        stage_0_5: 5.0
        stage_1: 5.0
        stage_1_5: 5.0
        stage_2: 5.0

        stage_2_5: 0.5
        stage_3: 0.5
        stage_3_5: 0.5
        stage_4: 0.5
        stage_4_5: 0.5
        stage_5: 0.5
      STAGE_ORDERING:
        - stage_bowl_1
        - stage_bowl_2
        - stage_bowl_3
        - stage_bowl_4
        - stage_bowl_5
        - stage_fruit_1
        - stage_fruit_2
        - stage_fruit_3
        - stage_fruit_4
        - stage_fruit_5

    INVALID_PDDL_ACTION_PENALTY:
      TYPE: InvalidPddlActionPenalty
      # This should be POSITIVE or 0
      PENALTY: 0.0
    SUM_INVALID_ACTION:
        TYPE: SumInvalidPddlAction
    DID_ROBOTS_COLLIDE:
      TYPE: DidRobotsCollide
    ROBOTS_DISTANCE:
      TYPE: RobotsDistance
    NUM_DID_ROBOTS_COLLIDE:
      TYPE: NumDidRobotsCollide
    DISTINCT_COLLIDE:
        TYPE: DistinctCollision
        GEO_COLL: True
        DIST_THRESH: 0.5
    NUM_DISINCT_COLLIDE:
        TYPE: NumDistinctCollide
    NUM_NAV_ACTIONS:
        TYPE: NumNavActions
    REL_POS_SENSOR:
      TYPE: RelativePositionsSensor
    COLL_INFO:
      TYPE: CollInfoSensor
    SUCCESS_NO_COLL:
      TYPE: SuccessNoColl
    MULTI_ROBOT_REL_OBJ_POS:
      TYPE: MultiRobotRelObjPosSensor
      N_TARGETS: 2
      N_ROBOTS: 2
    ACTION_HISTORY:
      TYPE: ActionHistorySensor
      WINDOW: 20
      STEPS: 500

    SENSORS:
      - IS_HOLDING_SENSOR
      - LOCALIZATION_SENSOR 
      - REL_POS_SENSOR
      - COLL_INFO
      - ACTION_HISTORY
      - MULTI_ROBOT_REL_OBJ_POS
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: -1.0
    ROBOT_FORCE:
        TYPE: RobotForce
        MIN_FORCE: 20.0
    AGENT_BLAME: 
        TYPE: AgentBlameMeasure
    MEASUREMENTS:
      - NUM_STEPS
      #- INVALID_PDDL_ACTION_PENALTY
      - DID_ROBOTS_COLLIDE
      - ROBOTS_DISTANCE
      - DISTINCT_COLLIDE
      - NUM_DISINCT_COLLIDE
      - NUM_DID_ROBOTS_COLLIDE
      - COOKING_REWARD
      #- SUM_INVALID_ACTION
      # - NUM_NAV_ACTIONS
      - COMPOSITE_SUCCESS
      #TODO: Temporary for debuging.
      - COMPOSITE_STAGE_GOALS
      - GFX_REPLAY_MEASURE
      # - EFFICIENCY
      # - SUCCESS_NO_COLL
      # - AGENT_BLAME
    ACTIONS:
      AGENT_0_ARM_ACTION:
          AGENT: 0
          TYPE: ArmAction
          ARM_CONTROLLER: ArmRelPosAction
          GRIP_CONTROLLER: MagicGraspAction
          ARM_JOINT_DIMENSIONALITY: 7
          GRASP_THRESH_DIST: 0.15
          DISABLE_GRIP: false
          DELTA_POS_LIMIT: 0.0125
          EE_CTRL_LIM: 0.015
      AGENT_0_BASE_VELOCITY:
          AGENT: 0
          TYPE: BaseVelAction
          LIN_SPEED: 40.0
          ANG_SPEED: 20.0
          ALLOW_DYN_SLIDE: False
          END_ON_STOP: false
          ALLOW_BACK: true
          MIN_ABS_LIN_SPEED: 1.0
          MIN_ABS_ANG_SPEED: 1.0
      AGENT_0_PDDL_APPLY_ACTION:
          AGENT: 0
          TYPE: PddlApplyAction
      AGENT_1_ARM_ACTION:
          AGENT: 1
          TYPE: ArmAction
          ARM_CONTROLLER: ArmRelPosAction
          GRIP_CONTROLLER: MagicGraspAction
          ARM_JOINT_DIMENSIONALITY: 7
          GRASP_THRESH_DIST: 0.15
          DISABLE_GRIP: false
          DELTA_POS_LIMIT: 0.0125
          EE_CTRL_LIM: 0.015
      AGENT_1_BASE_VELOCITY:
          AGENT: 1
          TYPE: BaseVelAction
          LIN_SPEED: 40.0
          ANG_SPEED: 20.0
          ALLOW_DYN_SLIDE: False
          END_ON_STOP: false
          ALLOW_BACK: true
          MIN_ABS_LIN_SPEED: 1.0
          MIN_ABS_ANG_SPEED: 1.0
      AGENT_1_PDDL_APPLY_ACTION:
          AGENT: 1
          TYPE: PddlApplyAction
      AGENT_0_REARRANGE_STOP:
          TYPE: RearrangeStopAction
      AGENT_1_REARRANGE_STOP:
          TYPE: RearrangeStopAction
      AGENT_0_ORACLE_NAV_ACTION:
          TYPE: "OracleNavAction"
          TURN_VELOCITY: 1.0
          FORWARD_VELOCITY: 1.0
          TURN_THRESH: 0.1
          DIST_THRESH: 0.2
          AGENT: 0
          LIN_SPEED: 40.0
          ANG_SPEED: 20.0
          MIN_ABS_LIN_SPEED: 1.0
          MIN_ABS_ANG_SPEED: 1.0
          ALLOW_DYN_SLIDE: False
          END_ON_STOP: False
          ALLOW_BACK: True
      AGENT_1_ORACLE_NAV_ACTION:
          TYPE: "OracleNavAction"
          TURN_VELOCITY: 1.0
          FORWARD_VELOCITY: 1.0
          TURN_THRESH: 0.1
          DIST_THRESH: 0.2
          AGENT: 1
          LIN_SPEED: 40.0
          ANG_SPEED: 20.0
          MIN_ABS_LIN_SPEED: 1.0
          MIN_ABS_ANG_SPEED: 1.0
          ALLOW_DYN_SLIDE: False
          END_ON_STOP: False
          ALLOW_BACK: True
    POSSIBLE_ACTIONS:
      - AGENT_0_ARM_ACTION
      - AGENT_0_BASE_VELOCITY
      - AGENT_0_PDDL_APPLY_ACTION
      - AGENT_0_REARRANGE_STOP
      - AGENT_0_ORACLE_NAV_ACTION
      - AGENT_1_ARM_ACTION
      - AGENT_1_BASE_VELOCITY
      - AGENT_1_PDDL_APPLY_ACTION
      - AGENT_1_REARRANGE_STOP
      - AGENT_1_ORACLE_NAV_ACTION
SIMULATOR:
    KINEMATIC_MODE: True
    STEP_PHYSICS: False
    MIN_AGENT_DIST: 1.0

    ACTION_SPACE_CONFIG: v0
    ADDITIONAL_OBJECT_PATHS:
     - "data/objects/ycb/configs/"
    GRASP_IMPULSE: 1000.0
    HOLD_THRESH: 0.09
    AC_FREQ_RATIO: 4
    CTRL_FREQ: 120.0
    DEBUG_RENDER: false
    DEBUG_N_RENDER: 2
    DEBUG_RENDER_GOAL: true
    NEEDS_MARKERS: false
    AGENTS:
    - AGENT_0
    - AGENT_1
    CONCUR_RENDER: false
    AUTO_SLEEP: false
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
        IS_SET_START_STATE: false
    AGENT_1:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS:
        - HEAD_DEPTH_SENSOR
        ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_suction_other.urdf
        ROBOT_TYPE: FetchSuctionRobot
        IK_ARM_URDF: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
        JOINT_START_NOISE: 0.0
        IS_SET_START_STATE: false
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: true
    DEFAULT_AGENT_ID: 0
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: true
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
        ENABLE_GFX_REPLAY_SAVE: False
    SEED: 100
    TYPE: RearrangeSim-v0
